hand:
  kinematic:
    x: -0.0455
    y: -0.048
    z: -0.005
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

left_finger:
  kinematic:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

right_finger:
  kinematic:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
